name: ${project.name}
main: ${project.mainclass}
version: ${project.version}
description: ${project.description}
author: Mics
website: https://mics.tw

commands:
  kill:
    description: kill yourself
    aliases: [suicide]
    usage: /kill