name: ${project.name}
main: ${project.mainclass}
version: ${project.version}
description: ${project.description}
author: Mics
website: https://mics.tw

depend: [Vault, ProtocolLib]
softdepend: [PowerfulPerms]

commands:
  kill:
    description: kill yourself
    aliases: [suicide]
    usage: /kill